<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>ClassicUs.OfficialRolesBackport</AssemblyName>
    <RootNamespace>ClassicUs.OfficialRolesBackport</RootNamespace>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>CS0626;CS0649;CS8632;CS0108</NoWarn>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClassicUs.GameLibs" Version="2026.8.17.1" PrivateAssets="all" />
    <PackageReference Include="ClassicUs.Manactor" Version="1.2.0" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="ClassicUs.ManuAPI" Version="1.5.3" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
